// Package commands provides CLI commands for SDK Forge.
package commands

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/spf13/cobra"

	"github.com/vubon/sdk-forge/internal/generator/common"
	gogen "github.com/vubon/sdk-forge/internal/generator/go"
	"github.com/vubon/sdk-forge/internal/generator/php"
	"github.com/vubon/sdk-forge/internal/generator/python"
	"github.com/vubon/sdk-forge/internal/generator/typescript"
	"github.com/vubon/sdk-forge/internal/parser"
	"github.com/vubon/sdk-forge/internal/validator"
	httplib "github.com/vubon/sdk-forge/pkg/languages/http"
)

const (
	langAll    = "all"
	langGo     = "go"
	langPython = "python"
)

var generateCmd = &cobra.Command{
	Use:   "generate",
	Short: "Generate SDKs from OpenAPI schema",
	Long: `Generate SDKs for multiple programming languages from OpenAPI schemas.
	
The generated SDK will be placed at: output/language/sdk-name/

Example:
  sdk-forge generate --schema ./openapi.yaml --lang python --name my-sdk --output ./sdks
  # Creates: ./sdks/python/my-sdk/`,
	RunE: runGenerate,
}

var (
	schemaPath    string
	language      string
	httpLib       string
	sdkName       string
	outputDir     string
	ignoreMinor   bool
	force         bool
	goVersion     string
	pythonVersion string
	phpVersion    string
	sdkVersion    string
	skipTests     bool
)

func init() {
	generateCmd.Flags().StringVarP(&schemaPath, "schema", "s", "", "Path or URL to OpenAPI schema (YAML/JSON) (required)")
	generateCmd.Flags().StringVarP(&language, "language", "l", "", "Target language: python, go, php, js, ts (required)")
	generateCmd.Flags().StringVar(&language, "lang", "", "Target language (alias for --language)")
	generateCmd.Flags().StringVar(&httpLib, "http-lib", "", "HTTP library to use (optional, uses default if not provided)")
	generateCmd.Flags().StringVarP(&sdkName, "name", "n", "", "Name for the generated SDK (required)")
	generateCmd.Flags().StringVarP(&outputDir, "output", "o", "", "Output directory for generated SDK (required)")
	generateCmd.Flags().BoolVar(&ignoreMinor, "ignore-minor-issues", false,
		"Ignore minor validation issues (major issues still block generation)")
	generateCmd.Flags().BoolVarP(&force, "force", "f", false, "Overwrite existing SDK directory")
	generateCmd.Flags().StringVar(&goVersion, "go-version", "",
		"Go version to use (e.g., 1.24, 1.25). Default: 1.24")
	generateCmd.Flags().StringVar(&pythonVersion, "python-version", "",
		"Python version to use (e.g., 3.11, 3.12, 3.13, 3.14). Default: 3.11")
	generateCmd.Flags().StringVar(&phpVersion, "php-version", "",
		"PHP version to use (e.g., 8.0, 8.1, 8.2, 8.3). Default: 8.1")
	generateCmd.Flags().StringVar(&sdkVersion, "sdk-version", "",
		"SDK version to use (e.g., 1.0.0, 2.0.0). "+
			"If not provided, uses OpenAPI schema version (if available) or defaults to 1.0.0")
	generateCmd.Flags().BoolVar(&skipTests, "skip-tests", false,
		"Skip test generation (tests are generated by default)")

	// Retry mechanism flags (read directly from flags in parseRetryConfig)
	generateCmd.Flags().Bool("retry-enabled", false,
		"Enable retry logic for failed HTTP requests (default: false)")
	generateCmd.Flags().Int("retry-max-attempts", 3,
		"Maximum retry attempts (default: 3)")
	generateCmd.Flags().Float64("retry-initial-delay", 1.0,
		"Initial retry delay in seconds (default: 1.0)")
	generateCmd.Flags().Float64("retry-max-delay", 60.0,
		"Maximum retry delay in seconds (default: 60.0)")
	generateCmd.Flags().Float64("retry-backoff-multiplier", 2.0,
		"Exponential backoff multiplier (default: 2.0)")
	generateCmd.Flags().String("retry-strategy", "exponential",
		"Retry strategy: exponential, linear, or fixed (default: exponential)")
	generateCmd.Flags().String("retry-status-codes", "429,500,502,503,504",
		"Comma-separated HTTP status codes to retry (default: 429,500,502,503,504)")

	// Don't mark flags as required - we handle validation in runGenerate
	// This allows interactive mode to work when flags are missing
}

func runGenerate(cmd *cobra.Command, _ []string) error {
	// Check if we need to run in interactive mode
	// Interactive mode: if any required flag is missing, prompt for it
	hasSchema, _ := cmd.Flags().GetString("schema")
	hasLang, _ := cmd.Flags().GetString("lang")
	hasLangLong, _ := cmd.Flags().GetString("language")
	hasName, _ := cmd.Flags().GetString("name")
	hasOutput, _ := cmd.Flags().GetString("output")

	// If any required info is missing, run interactive mode
	if hasSchema == "" || (hasLang == "" && hasLangLong == "") || hasName == "" || hasOutput == "" {
		if err := RunInteractive(cmd); err != nil {
			return err
		}
	}

	// Re-read flags from command (they may have been set by interactive mode)
	schemaPath, _ = cmd.Flags().GetString("schema")
	sdkName, _ = cmd.Flags().GetString("name")
	outputDir, _ = cmd.Flags().GetString("output")
	httpLib, _ = cmd.Flags().GetString("http-lib")
	ignoreMinor, _ = cmd.Flags().GetBool("ignore-minor-issues")
	force, _ = cmd.Flags().GetBool("force")
	sdkVersion, _ = cmd.Flags().GetString("sdk-version")
	skipTests, _ = cmd.Flags().GetBool("skip-tests")

	// Validate required flags after interactive mode (in case user didn't provide them)
	if schemaPath == "" {
		return fmt.Errorf("schema is required. Use --schema or -s")
	}
	if sdkName == "" {
		return fmt.Errorf("name is required. Use --name or -n")
	}
	if outputDir == "" {
		return fmt.Errorf("output is required. Use --output or -o")
	}

	// Get language from either --lang or --language flag
	// Since both are bound to the same variable, check which one was set
	langFlag := cmd.Flag("lang")
	langFlagLong := cmd.Flag("language")

	var lang string
	switch {
	case langFlag != nil && langFlag.Changed:
		lang = langFlag.Value.String()
	case langFlagLong != nil && langFlagLong.Changed:
		lang = langFlagLong.Value.String()
	default:
		// Try reading from flags directly (for interactive mode)
		lang, _ = cmd.Flags().GetString("lang")
		if lang == "" {
			lang, _ = cmd.Flags().GetString("language")
		}
		if lang == "" {
			// Fallback to variable (in case cobra doesn't detect change)
			lang = language
		}
	}

	if lang == "" {
		return fmt.Errorf("language is required. Use --lang or --language")
	}

	// Normalize language (handle aliases)
	normalizedLang := validator.NormalizeLanguage(lang)

	// Validate language
	if err := validator.ValidateLanguage(normalizedLang); err != nil {
		return err
	}

	// Parse and validate OpenAPI schema once (shared for all languages if using --lang all)
	fmt.Printf("✓ Parsing OpenAPI schema... ")

	doc, err := parser.ParseOpenAPI(schemaPath)
	if err != nil {
		return fmt.Errorf("failed to parse OpenAPI schema: %w", err)
	}

	// Validate schema
	parseResult, err := parser.ValidateOpenAPI(doc, ignoreMinor)
	if err != nil {
		return fmt.Errorf("failed to validate OpenAPI schema: %w", err)
	}

	// Check if there are blocking errors
	if len(parseResult.Errors) > 0 {
		errorMsg := parser.FormatValidationErrors(parseResult)
		return fmt.Errorf("OpenAPI validation failed:\n%s", errorMsg)
	}

	if len(parseResult.Warnings) > 0 {
		fmt.Printf("OK (with %d warnings)\n", len(parseResult.Warnings))
	} else {
		fmt.Println("OK")
	}

	// Handle --lang all
	if normalizedLang == langAll {
		return generateAllLanguages(outputDir, sdkName, httpLib, doc, force, cmd)
	}

	// Validate SDK name for single language
	if _, err := validator.ValidateSDKName(sdkName, normalizedLang); err != nil {
		return err
	}

	// Validate or get default HTTP library
	finalHTTPLib, err := httplib.ValidateOrGetDefault(normalizedLang, httpLib)
	if err != nil {
		return fmt.Errorf("HTTP library validation failed: %w", err)
	}

	// Build output path: output/language/sdk-name/
	sdkOutputPath := filepath.Join(outputDir, normalizedLang, sdkName)

	// Check if output directory exists
	if _, err := os.Stat(sdkOutputPath); err == nil {
		if !force {
			return fmt.Errorf("SDK directory already exists: %s\nUse --force to overwrite", sdkOutputPath)
		}
	}

	// Create output directory structure
	if err := os.MkdirAll(sdkOutputPath, 0750); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	fmt.Printf("✓ Creating output directory... %s\n", sdkOutputPath)
	fmt.Printf("✓ Validating HTTP library... OK (%s)\n", finalHTTPLib)
	fmt.Printf("✓ Generating SDK code... ")

	// Generate SDK based on language
	if err := generateSDKForLanguage(normalizedLang, sdkOutputPath, sdkName, finalHTTPLib, doc, cmd); err != nil {
		return err
	}

	fmt.Println("OK")
	fmt.Printf("\n✅ SDK generated successfully at: %s\n", sdkOutputPath)

	return nil
}

// generateAllLanguages generates SDKs for all implemented languages
func generateAllLanguages(outputDir, sdkName, httpLib string, doc interface{}, force bool, cmd *cobra.Command) error {
	implementedLangs := validator.GetImplementedLanguages()

	fmt.Printf("✓ Generating SDKs for all languages: %v\n", implementedLangs)
	fmt.Println()

	var errors []string
	successCount := 0

	for _, lang := range implementedLangs {
		fmt.Printf("Generating %s SDK...\n", lang)

		// Validate SDK name for this language
		if _, err := validator.ValidateSDKName(sdkName, lang); err != nil {
			errors = append(errors, fmt.Sprintf("%s: %v", lang, err))
			continue
		}

		// Validate or get default HTTP library
		finalHTTPLib, err := httplib.ValidateOrGetDefault(lang, httpLib)
		if err != nil {
			errors = append(errors, fmt.Sprintf("%s: HTTP library validation failed: %v", lang, err))
			continue
		}

		// Build output path: output/language/sdk-name/
		sdkOutputPath := filepath.Join(outputDir, lang, sdkName)

		// Check if output directory exists
		if _, err := os.Stat(sdkOutputPath); err == nil {
			if !force {
				errors = append(errors,
					fmt.Sprintf("%s: SDK directory already exists: %s (use --force to overwrite)",
						lang, sdkOutputPath))
				continue
			}
		}

		// Create output directory structure
		if err := os.MkdirAll(sdkOutputPath, 0750); err != nil {
			errors = append(errors, fmt.Sprintf("%s: failed to create output directory: %v", lang, err))
			continue
		}

		fmt.Printf("  ✓ Validating HTTP library... OK (%s)\n", finalHTTPLib)
		fmt.Printf("  ✓ Generating SDK code... ")

		// Generate SDK for this language
		if err := generateSDKForLanguage(lang, sdkOutputPath, sdkName, finalHTTPLib, doc, cmd); err != nil {
			errors = append(errors, fmt.Sprintf("%s: %v", lang, err))
			fmt.Println("FAILED")
			continue
		}

		fmt.Println("OK")
		fmt.Printf("  ✅ %s SDK generated at: %s\n", lang, sdkOutputPath)
		fmt.Println()
		successCount++
	}

	// Summary
	fmt.Println("=== Generation Summary ===")
	fmt.Printf("✓ Successfully generated: %d/%d SDKs\n", successCount, len(implementedLangs))

	if len(errors) > 0 {
		fmt.Printf("✗ Errors: %d\n", len(errors))
		for _, err := range errors {
			fmt.Printf("  - %s\n", err)
		}
		return fmt.Errorf("failed to generate some SDKs: %d errors", len(errors))
	}

	fmt.Printf("\n✅ All SDKs generated successfully!\n")
	return nil
}

// generateSDKForLanguage generates SDK for a specific language
func generateSDKForLanguage(lang, outputPath, sdkName, httpLib string, doc interface{}, cmd *cobra.Command) error {
	var goVer *common.LanguageVersion
	var pythonVer *common.LanguageVersion
	var phpVer *common.LanguageVersion

	// Get SDK version from flag (if provided)
	sdkVerStr, _ := cmd.Flags().GetString("sdk-version")

	// Parse version flags if provided
	if lang == langGo || lang == langAll {
		goVerStr, _ := cmd.Flags().GetString("go-version")
		if goVerStr != "" {
			parsed, err := common.ParseVersion(goVerStr)
			if err != nil {
				return fmt.Errorf("invalid Go version: %w", err)
			}
			if err := common.ValidateGoVersion(parsed); err != nil {
				return err
			}
			goVer = &parsed
		}
	}

	if lang == langPython || lang == langAll {
		pythonVerStr, _ := cmd.Flags().GetString("python-version")
		if pythonVerStr != "" {
			parsed, err := common.ParseVersion(pythonVerStr)
			if err != nil {
				return fmt.Errorf("invalid Python version: %w", err)
			}
			if err := common.ValidatePythonVersion(parsed); err != nil {
				return err
			}
			pythonVer = &parsed
		}
	}

	if lang == "php" || lang == langAll {
		phpVerStr, _ := cmd.Flags().GetString("php-version")
		if phpVerStr != "" {
			parsed, err := common.ParseVersion(phpVerStr)
			if err != nil {
				return fmt.Errorf("invalid PHP version: %w", err)
			}
			if err := common.ValidatePHPVersion(parsed); err != nil {
				return err
			}
			phpVer = &parsed
		}
	}

	// Get skip-tests flag (inverted: if skipTests is true, generateTests is false)
	skipTestsFlag, _ := cmd.Flags().GetBool("skip-tests")
	generateTests := !skipTestsFlag

	// Parse retry configuration from flags and OpenAPI extension
	// First try to get retry config from OpenAPI document
	var retryConfig common.RetryConfig
	if openapiDoc, ok := doc.(*openapi3.T); ok {
		openAPIRetryConfig := common.ParseRetryConfigFromOpenAPI(openapiDoc)
		cliRetryConfig := parseRetryConfig(cmd)

		// Merge: OpenAPI extension provides defaults, CLI flags override
		if openAPIRetryConfig != nil {
			retryConfig = common.MergeRetryConfig(*openAPIRetryConfig, cliRetryConfig)
		} else {
			retryConfig = cliRetryConfig
		}
	} else {
		// If not openapi3.T, just use CLI flags
		retryConfig = parseRetryConfig(cmd)
	}

	switch lang {
	case langPython:
		return python.GeneratePythonSDK(outputPath, sdkName, httpLib, doc, pythonVer, sdkVerStr, generateTests, retryConfig)
	case langGo:
		return gogen.GenerateGoSDK(outputPath, sdkName, httpLib, doc, goVer, sdkVerStr, generateTests, retryConfig)
	case "php":
		return php.GeneratePHPSDK(outputPath, sdkName, httpLib, doc, phpVer, sdkVerStr, generateTests, retryConfig)
	case "javascript", "typescript":
		// TypeScript version is not used yet, but reserved for future use
		return typescript.GenerateTypeScriptSDK(outputPath, sdkName, httpLib, doc, nil, sdkVerStr, generateTests, retryConfig)
	default:
		return fmt.Errorf("unsupported language: %s", lang)
	}
}

// parseRetryConfig parses retry configuration from command flags
func parseRetryConfig(cmd *cobra.Command) common.RetryConfig {
	config := common.DefaultRetryConfig()

	// Get retry flags
	retryEnabled, _ := cmd.Flags().GetBool("retry-enabled")
	retryMaxAttempts, _ := cmd.Flags().GetInt("retry-max-attempts")
	retryInitialDelay, _ := cmd.Flags().GetFloat64("retry-initial-delay")
	retryMaxDelay, _ := cmd.Flags().GetFloat64("retry-max-delay")
	retryBackoffMult, _ := cmd.Flags().GetFloat64("retry-backoff-multiplier")
	retryStrategy, _ := cmd.Flags().GetString("retry-strategy")
	retryStatusCodes, _ := cmd.Flags().GetString("retry-status-codes")

	config.Enabled = retryEnabled
	if retryMaxAttempts > 0 {
		config.MaxAttempts = retryMaxAttempts
	}
	if retryInitialDelay > 0 {
		config.InitialDelay = time.Duration(retryInitialDelay * float64(time.Second))
	}
	if retryMaxDelay > 0 {
		config.MaxDelay = time.Duration(retryMaxDelay * float64(time.Second))
	}
	if retryBackoffMult > 0 {
		config.BackoffMultiplier = retryBackoffMult
	}

	// Parse retry strategy
	switch strings.ToLower(retryStrategy) {
	case "exponential":
		config.Strategy = common.RetryStrategyExponential
	case "linear":
		config.Strategy = common.RetryStrategyLinear
	case "fixed":
		config.Strategy = common.RetryStrategyFixed
	default:
		config.Strategy = common.RetryStrategyExponential
	}

	// Parse retryable status codes
	if retryStatusCodes != "" {
		codes := []int{}
		parts := strings.Split(retryStatusCodes, ",")
		for _, part := range parts {
			part = strings.TrimSpace(part)
			if code, err := strconv.Atoi(part); err == nil {
				codes = append(codes, code)
			}
		}
		if len(codes) > 0 {
			config.RetryableStatusCodes = codes
		}
	}

	return config
}

// GetGenerateCmd returns the generate command
func GetGenerateCmd() *cobra.Command {
	return generateCmd
}
